# Generated by Django 3.0.2 on 2020-08-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_secret_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='User Secret Key'),
        ),
    ]
