# Generated by Django 3.0.2 on 2020-08-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhint',
            name='password_hint_two',
            field=models.TextField(blank=True, null=True, verbose_name='Second Hint'),
        ),
    ]
