# Generated by Django 3.0.2 on 2020-08-19 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passwords', '0002_auto_20200815_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_belongs_to', models.CharField(max_length=100)),
                ('password_description', models.TextField(blank=True, null=True)),
                ('encrypted_password', models.CharField(max_length=1000)),
                ('security_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Generated Passwords',
            },
        ),
    ]
